export const elements = [
  {
    type: "text",
    value: "avatar",
    name: "avatar",
    placeholder: "Paste your avatar",
    messageInvalid: "",
    isValid: "",
  },
  {
    type: "text",
    value: "name",
    name: "name",
    placeholder: "Type your name",
    messageInvalid: "",
    isValid: "",
  },
  {
    type: "text",
    value: "lastname",
    name: "lastname",
    placeholder: "Type your lastname",
    messageInvalid: "",
    isValid: "",
  },
  {
    type: "email",
    value: "email",
    name: "email",
    placeholder: "Type your email",
    messageInvalid: "Ingresa un correo valido",
    isValid: "isValidEmail",
  },
  {
    type: "password",
    value: "password",
    name: "password",
    placeholder: "Type your password",
    messageInvalid: "Ingresa un password valido",
    isValid: "isValidPassword",
  },
];
